version: 2
updates:
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "*"
        update-types:
        - "version-update:semver-major"
    groups:
      k8s:
        patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
